class FilterContents {
  FilterContents._();
  // static const String

  static const List<String> skills = [
    "Networking",
    "Software Testing",
    "SAP abap",
    "Call Center",
    "Mainframe",
    "SAP FICO",
    "SAP",
    "SEO",
    ".NET",
    "Oracle",
    "PHP",
    "Back office",
    "Java",
    "Online Marketing",
    "SAP Basis",
    "SAS",
    "CISCO",
    "Manual Testing",
    "SAP HR",
    "SAP MM",
    "SAP SD",
    "SAP Security",
    "VLSI",
    "Web Designing",
    "CCIE",
    "Informatica",
    "Linux",
    "PeopleSoft",
    "Plc",
    "SQL",
    "ASP.NET",
    "Datastage",
    "Finacle",
    "SAP CRM",
    "Tally",
    "Tibco",
    "CATIA",
    "Cognos",
    "ITIL",
    "Multimedia",
    "Photoshop",
    "PRO E",
    "ABAP",
    "Backend",
    "C",
    "DTP",
    "ERP",
    "Internet Marketing",
    "Siebel",
    "Video Editing",
    "AbInitio",
    "CAD/CAM",
    "Digital Marketing",
    "Editing",
    "HTML",
    "Oracle Apps",
    "Perl",
    "Python",
    "SAP PP",
    "SAP PS",
    "SQL Server",
    "Database",
    "MCSE",
    "PPC",
    "QTP",
    "SAP PM",
    "Teradata",
    "CRM",
    "data warehousing",
    "Excel",
    "Flexcube",
    "MATLAB",
    "PowerBuilder",
    "SAP BW",
    "Solaris",
    "AIX",
    "ArchiCAD",
    "Business Objects",
    "Documentum",
    "FACT",
    "Flex",
    "Hyperion",
    "SCADA",
    "UniGraphics",
    "Unix",
    "Vision Plus",
    "VSAT",
    "WebMethods",
    "Auto CAD",
    "Datawarehousing",
    "Flash",
    "Lotus Notes",
    "Maximo",
    "Primavera",
    "SAP IS-Retail",
    "Autosys",
    "COBOL",
    "ColdFusion",
    "Maya",
    "Programming",
    "RIM",
    "SAP MDM",
    "XML",
    "D Max",
    "Automation Testing",
    "BAAN",
    "C#",
    "Delphi",
    "JEE",
    "MySQL",
    "RedHat",
    "SAP EP",
    "SAP SRM",
    "TPF",
    "VB.NET",
    "VOIP",
    "WebLogic",
    "WebSphere",
    "Active Directory",
    "Ansys",
    "Data Analysis",
    "Documentation",
    "DSP",
    "IMS",
    "Remedy",
    "SAP QM",
    "SPSS",
    "Sybase",
    "TLM",
    "ASIC",
    "Blackberry",
    "Corel Draw",
    "CSS",
    "DB",
    "Embedded C",
    "FileNet",
    "FoxPro",
    "FPGA",
    "JME",
    "JavaScript",
    "MCSA",
    "Murex",
    "SAP XI",
    "WPF",
    "Adobe Photoshop",
    "DCA",
    "Distribution",
    "Jquery",
    "Natural Adabas",
    "ORCAD",
    "ProgressGL",
    "SAP SCM",
    "Silverlight",
    "Switching",
    "Android Development",
    "ASP",
    "Calypso",
    "GSM",
    "Load Runner",
    "MCP",
    "MicroStation",
    "MSCIT",
    "Savvion",
    "Shell Scripting",
    "Spring",
    "Visual Basic",
    "Affiliate Marketing",
    "Eclipse",
    "Focus",
    "ForTran",
    "HP UNIX",
    "JSF",
    "MFC",
    "SAP IS-Utilities",
    "Verilog",
    "Visual Foxpro",
    "WCF",
    "Website Development",
    "Dreamweaver",
    "IIS",
    "JSP",
    "Microsoft Excel",
    "Nortel",
    "RDO",
    "ActiveX",
    "ADO",
    "Adobe Illustrator",
    "Adobe Pagemaker",
    "AJAX",
    "ALE",
    "Ant",
    "Apache Commons",
    "Apache Tomcat",
    "Apache Web Server",
    "AS",
    "Assembly Language",
    "ATL",
    "AutoLISP",
    "AWT",
    "BASIC",
    "Bluetooth",
    "BPCS",
    "BPEL",
    "BREW",
    "C++",
    "CDMA",
    "Chordiant",
    "CICS",
    "CLDC",
    "Clipper",
    "COM/COM+/DCOM",
    "CORBA",
    "CoreJava",
    "Crystal Report",
    "Csharp",
    "Data Structures",
    "Database Administration",
    "Dbo",
    "dBase",
    "DCOM",
    "Derby",
    "Developer/DK",
    "DHCP",
    "DHTML",
    "DNS",
    "DOS",
    "Downstream",
    "EJB",
    "Ethernet",
    "Expeditor",
    "Finone",
    "Firewall",
    "Fireworks",
    "FlashLite",
    "FreeBSD",
    "FTP",
    "GLOSS",
    "Hibernate",
    "Humming Bird",
    "iBatis",
    "Ideas",
    "ImageReady",
    "Impromptu",
    "Informix",
    "Ingres",
    "Installshield",
    "ISDN",
    "J++",
    "JSE",
    "JavaD",
    "JavaCard",
    "JavaFX",
    "JavaSE",
    "JBoss",
    "JBoss Seam",
    "JCL",
    "JDBC",
    "JDOM",
    "JFace",
    "Jini",
    "JIRA",
    "JMock",
    "JMS",
    "JNI",
    "JPA",
    "JSE",
    "JUnit",
    "Kickboxing",
    "KSH",
    "LAN",
    "LINQ",
    "Logj",
    "Mac OS",
    "Maven",
    "Microcontrollers",
    "Microprocessors",
    "Microsoft Access",
    "Microsoft Exchange",
    "Microsoft Office",
    "MIDP",
    "MIS Reports",
    "MOSS",
    "Motif",
    "MS DOS",
    "MS Project",
    "MS SQL Server",
    "MS Visio",
    "Multithreading",
    "MVS",
    "NetWeaver",
    "Novell",
    "ODBC",
    "Office Operations",
    "OOPS",
    "OpenGL ES",
    "Operating Systems",
    "Oracle WareHouse Builder",
    "PASCAL",
    "PL/SQL",
    "PL/",
    "PostgreSQL",
    "PowerPlay",
    "Pro*C",
    "PVCS",
    "QBasic",
    "Quality Assurance/QA",
    "Remoting",
    "REXX",
    "RichFaces",
    "RMI",
    "Routing",
    "RTOS",
    "S",
    "SAP Bl",
    "SAP COPA",
    "SAP idocs",
    "SAP IS-GAS/OIL",
    "SAP Practice",
    "SAP SEM",
    "SAP WMS",
    "Seam",
    "Sharepoint Server",
    "SMARTY",
    "SMTP",
    "SoundForge",
    "STAAD",
    "Struts",
    "SunOS",
    "SWT",
    "Symbian C++",
    "Symbian",
    "SyncML",
    "T SQL",
    "TCP/IP",
    "TELNET",
    "TOAD",
    "Turbo Pascal",
    "Tuxedo",
    "UIQ",
    "UML",
    "Upstream",
    "VBScript",
    "Vi",
    "Vignette",
    "Visual C++",
    "Visual Interdev",
    "VMS",
    "VPN",
    "VSS/Clearcase",
    "VxWorks",
    "WAN",
    "WAP",
    "Winform",
    "Winrunner",
    "WML",
    "XDoclet",
    "Xenix",
    "XHTML",
    "XStream",
    "Yantra",
    "Designing",
    "SMO",
    "VAX/VMS",
    "TCL/TK",
    "Back office Operations",
    "OS/",
    "SAP BI",
    "Sharepoint MOSS",
    "Banking",
    "Biotechnology",
    "Teaching",
    "Finance",
    "Marketing",
    "Nursing",
    "Animation",
    "Accounting",
    "Accounts",
    "Graphic Design",
    "HVAC",
    "Administration",
    "Journalism",
    "Sales",
    "Writing",
    "Manufacturing",
    "Photography",
    "Advertising",
    "Income Tax",
    "Interior Design",
    "Architecture",
    "Education",
    "Supply Chain",
    "Corporate Finance",
    "Design",
    "Yoga",
    "Acting",
    "Copywriting",
    "Jewellery",
    "Recruitment",
    "Visual Merchandising",
    "Music",
    "Training",
    "Entertainment",
    "Telemarketing",
    "Weaving",
    "Art",
    "Counselling",
    "Film Editing",
    "Hiring",
    "Human Resource Management",
    "Knowledge Management",
    "Landscape Architecture",
    "Plumbing",
    "Taxation",
    "Waste Management",
    "Astrology",
    "Baking",
    "Bookkeeping",
    "Illustration",
    "Lighting",
    "Office Administration",
    "Sales Tax",
    "Cost Accounting",
    "Email Marketing",
    "Talent Acquisition",
    "Textile Designing",
    "Cooking",
    "Dance",
    "Screen Printing",
    "Coaching",
    "IT Recruitment",
    "Vendor Management",
    "Analysis",
    "Banking Insurance",
    "Office Management",
    "Accounts Management",
    "Advertisement Sales",
    "Advertising Account Management",
    "Advertising Art Direction",
    "Advisory",
    "Aquisitions",
    "Art Therapy",
    "Authoring",
    "Body Art",
    "Bookbinding",
    "Busines Analysis",
    "Buying",
    "Channel Account Management",
    "Chartered Accountancy",
    "Cloth Design",
    "Company Laws",
    "Composing",
    "Curating",
    "Customer Relations",
    "Document Administration",
    "Electrical Distribution",
    "Floristry",
    "Guest Service",
    "Hairdressing",
    "Headhunting",
    "Image Consulting",
    "Industrial Designing",
    "Key Accounts Management",
    "Landscape Gardening",
    "Make up Art",
    "Map Making",
    "Mathematical",
    "Merchandise",
    "Mergers",
    "Motivating Skill",
    "Negotiating Skill",
    "Personal Services",
    "Planning and Organising",
    "Private Tutoring",
    "Producing",
    "Record Producing",
    "Sales Accounting",
    "Sales Planning",
    "Store planning",
    "Supervising",
    "Tax Audits",
    "Tax Laws",
    "Instructing",
    "Telling",
    "Therapy",
    "Trade Execution",
    "Upholstery",
    "Vehicle Operating",
    "Visa Expat Management",
    "Wine making",
    "ReactJS",
    "Redux",
    "Node JS",
  ];

  static const List<String> location = [
    "Adilabad",
    "Agra",
    "Noida",
    "Ahmedabad",
    "Ahmednagar",
    "Aizawl",
    "Ajitgarh (Mohali)",
    "Ajmer",
    "Akola",
    "Alappuzha",
    "Aligarh",
    "Alirajpur  ",
    "Allahabad",
    "Almora",
    "Alwar",
    "Ambala",
    "Ambedkar Nagar",
    "Amravati",
    "Amreli district",
    "Amritsar",
    "Anand",
    "Anantapur",
    "Anantnag",
    "Angul",
    "Anjaw",
    "Anuppur",
    "Araria",
    "Ariyalur",
    "Arwal",
    "Ashok Nagar",
    "Auraiya",
    "Aurangabad",
    "Aurangabad",
    "Azamgarh",
    "Badgam",
    "Bagalkot",
    "Bageshwar",
    "Bagpat",
    "Bahraich",
    "Baksa",
    "Balaghat",
    "Balangir",
    "Balasore",
    "Ballia",
    "Balrampur",
    "Banaskantha",
    "Banda",
    "Bandipora",
    "Bangalore Rural",
    "Bangalore Urban",
    "Banka",
    "Bankura",
    "Banswara",
    "Barabanki",
    "Baramulla",
    "Baran",
    "Bardhaman",
    "Bareilly",
    "Bargarh (Baragarh)",
    "Barmer",
    "Barnala",
    "Barpeta",
    "Barwani",
    "Bastar",
    "Basti",
    "Bathinda",
    "Beed",
    "Begusarai",
    "Belgaum",
    "Bellary",
    "Betul",
    "Bhadrak",
    "Bhagalpur",
    "Bhandara",
    "Bharatpur",
    "Bharuch",
    "Bhavnagar",
    "Bhind",
    "Bhiwani",
    "Bhojpur",
    "Bhopal",
    "Bidar",
    "Bijapur",
    "Bijnor",
    "Bikaner",
    "Bilaspur",
    "Birbhum",
    "Bishnupur",
    "Bokaro",
    "Bongaigaon",
    "Boudh (Bauda) ",
    "Budaun",
    "Bulandshahr",
    "Buldhana",
    "Bundi",
    "Burhanpur",
    "Buxar",
    "Cachar",
    "Central Delhi",
    "Chamarajnagar",
    "Chamba",
    "Chamoli",
    "Champawat",
    "Champhai",
    "Chandauli",
    "Chandel",
    "Chandigarh",
    "Chandrapur",
    "Changlang",
    "Chatra",
    "Chennai",
    "Chhatarpur",
    "Chhindwara",
    "Chikkaballapur",
    "Chikkamagaluru",
    "Chirang",
    "Chitradurga  ",
    "Chitrakoot",
    "Chittoor",
    "Chittorgarh",
    "Churachandpur",
    "Churu",
    "Coimbatore",
    "Cooch Behar",
    "Cuddalore",
    "Cuttack",
    "Dadra and Nagar Haveli",
    "Dahod",
    "Dakshin Dinajpur",
    "Dakshina Kannada",
    "Daman",
    "Damoh",
    "Dantewada",
    "Darbhanga",
    "Darjeeling",
    "Darrang",
    "Datia",
    "Dausa",
    "Davanagere",
    "Debagarh (Deogarh)",
    "Dehradun",
    "Deoghar",
    "Deoria",
    "Dewas",
    "Dhalai",
    "Dhamtari",
    "Dhanbad",
    "Dhar ",
    "Dharmapuri",
    "Dharwad",
    "Dhemaji",
    "Dhenkanal",
    "Dholpur",
    "Dhubri",
    "Dhule",
    "Dibang Valley",
    "Dibrugarh",
    "Dima Hasao",
    "Dimapur",
    "Dindigul",
    "Dindori",
    "Diu",
    "Doda",
    "Dumka",
    "Dungapur",
    "Durg",
    "East Champaran",
    "East Delhi",
    "East Garo Hills",
    "East Khasi Hills",
    "East Siang",
    "East Sikkim",
    "East Singhbhum",
    "Eluru",
    "Ernakulam",
    "Erode",
    "Etah",
    "Etawah",
    "Faizabad",
    "Faridabad",
    "Faridkot",
    "Farrukhabad",
    "Fatehabad",
    "Fatehgarh Sahib",
    "Fatehpur",
    "Fazilka",
    "Firozabad",
    "Firozpur",
    "Gadag",
    "Gadchiroli",
    "Gajapati",
    "Ganderbal",
    "Gandhinagar",
    "Ganganagar",
    "Ganjam",
    "Garhwa",
    "Gautam Buddh Nagar",
    "Gaya",
    "Ghaziabad",
    "Ghazipur",
    "Giridih",
    "Goalpara",
    "Godda",
    "Golaghat",
    "Gonda",
    "Gondia",
    "Gopalganj",
    "Gorakhpur",
    "Gulbarga",
    "Gumla",
    "Guna",
    "Guntur",
    "Gurdaspur",
    "Gurgaon",
    "Gwalior",
    "Hailakandi",
    "Hamirpur",
    "Hanumangarh",
    "Harda",
    "Hardoi",
    "Haridwar",
    "Hassan",
    "Haveri district",
    "Hazaribag",
    "Hingoli",
    "Hissar",
    "Hooghly",
    "Hoshangabad",
    "Hoshiarpur",
    "Howrah",
    "Hyderabad",
    "Idukki",
    "Imphal East",
    "Imphal West",
    "Indore",
    "Jabalpur",
    "Jagatsinghpur",
    "Jaintia Hills",
    "Jaipur",
    "Jaisalmer",
    "Jajpur",
    "Jalandhar",
    "Jalaun",
    "Jalgaon",
    "Jalna",
    "Jalore",
    "Jalpaiguri",
    "Jammu",
    "Jamnagar",
    "Jamtara",
    "Jamui",
    "Janjgir-Champa",
    "Jashpur",
    "Jaunpur district",
    "Jehanabad",
    "Jhabua",
    "Jhajjar",
    "Jhalawar",
    "Jhansi",
    "Jharsuguda",
    "Jhunjhunu",
    "Jind",
    "Jodhpur",
    "Jorhat",
    "Junagadh",
    "Jyotiba Phule Nagar",
    "Kabirdham (formerly Kawardha)",
    "Kadapa",
    "Kaimur",
    "Kaithal",
    "Kakinada",
    "Kalahandi",
    "Kamrup",
    "Kamrup Metropolitan",
    "Kanchipuram",
    "Kandhamal",
    "Kangra",
    "Kanker",
    "Kannauj",
    "Kannur",
    "Kanpur",
    "Kanshi Ram Nagar",
    "Kanyakumari",
    "Kapurthala",
    "Karaikal",
    "Karauli",
    "Karbi Anglong",
    "Kargil",
    "Karimganj",
    "Karimnagar",
    "Karnal",
    "Karur",
    "Kasaragod",
    "Kathua",
    "Katihar",
    "Katni",
    "Kaushambi",
    "Kendrapara",
    "Kendujhar (Keonjhar)",
    "Khagaria",
    "Khammam",
    "Khandwa (East Nimar)",
    "Khargone (West Nimar)",
    "Kheda",
    "Khordha",
    "Khowai",
    "Khunti",
    "Kinnaur",
    "Kishanganj",
    "Kishtwar",
    "Kodagu",
    "Koderma",
    "Kohima",
    "Kokrajhar",
    "Kolar",
    "Kolasib",
    "Kolhapur",
    "Kolkata",
    "Kollam",
    "Koppal",
    "Koraput",
    "Korba",
    "Koriya",
    "Kota",
    "Kottayam",
    "Kozhikode",
    "Krishna",
    "Kulgam",
    "Kullu",
    "Kupwara",
    "Kurnool",
    "Kurukshetra",
    "Kurung Kumey",
    "Kushinagar",
    "Kutch",
    "Lahaul and Spiti",
    "Lakhimpur",
    "Lakhimpur Kheri",
    "Lakhisarai",
    "Lalitpur",
    "Latehar",
    "Latur",
    "Lawngtlai",
    "Leh",
    "Lohardaga",
    "Lohit",
    "Lower Dibang Valley",
    "Lower Subansiri",
    "Lucknow",
    "Ludhiana",
    "Lunglei",
    "Madhepura",
    "Madhubani",
    "Madurai",
    "Mahamaya Nagar",
    "Maharajganj",
    "Mahasamund",
    "Mahbubnagar",
    "Mahe ",
    "Mahendragarh",
    "Mahoba",
    "Mainpuri",
    "Malappuram",
    "Maldah",
    "Malkangiri",
    "Mamit",
    "Mandi",
    "Mandla",
    "Mandsaur",
    "Mandya",
    "Mansa",
    "Marigaon",
    "Mathura",
    "Mau",
    "Mayurbhanj",
    "Medak",
    "Meerut",
    "Mehsana",
    "Mewat",
    "Mirzapur",
    "Moga",
    "Mokokchung",
    "Mon",
    "Moradabad",
    "Morena",
    "Mumbai City",
    "Mumbai suburban",
    "Munger",
    "Murshidabad",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mysore",
    "Nabarangpur",
    "Nadia",
    "Nagaon",
    "Nagapattinam",
    "Nagaur",
    "Nagpur",
    "Nainital",
    "Nalanda",
    "Nalbari",
    "Nalgonda",
    "Namakkal",
    "Nanded",
    "Nandurbar",
    "Narayanpur",
    "Narmada",
    "Narsinghpur",
    "Nashik",
    "Navsari",
    "Nawada",
    "Nawanshahr",
    "Nayagarh",
    "Neemuch",
    "Nellore",
    "New Delhi",
    "Nilgiris",
    "Nizamabad",
    "North  Parganas",
    "North Delhi",
    "North East Delhi",
    "North Goa",
    "North Sikkim",
    "North Tripura",
    "North West Delhi",
    "Nuapada",
    "Ongole",
    "Osmanabad",
    "Pakur",
    "Palakkad",
    "Palamu",
    "Pali",
    "Palwal",
    "Panchkula",
    "Panchmahal",
    "Panipat",
    "Panna",
    "Papum Pare",
    "Parbhani",
    "Paschim Medinipur",
    "Patan",
    "Pathanamthitta",
    "Pathankot",
    "Patiala",
    "Patna",
    "Pauri Garhwal",
    "Perambalur",
    "Phek",
    "Pilibhit",
    "Pithoragarh",
    "Pondicherry",
    "Poonch",
    "Porbandar",
    "Pratapgarh",
    "Pratapgarh",
    "Pudukkottai",
    "Pulwama",
    "Pune",
    "Purba Medinipur",
    "Puri",
    "Purnia ",
    "Purulia",
    "Raebareli",
    "Raichur",
    "Raigad",
    "Raigarh",
    "Raipur",
    "Raisen",
    "Rajauri",
    "Rajgarh",
    "Rajkot",
    "Rajnandgaon",
    "Rajsamand",
    "Ramanagara",
    "Ramanathapuram",
    "Ramban",
    "Ramgarh",
    "Rampur",
    "Ranchi",
    "Ratlam",
    "Ratnagiri",
    "Rayagada",
    "Reasi",
    "Rewa",
    "Rewari",
    "Ri Bhoi",
    "Rohtak",
    "Rohtas",
    "Rudraprayag",
    "Rupnagar",
    "Sabarkantha",
    "Sagar",
    "Saharanpur",
    "Saharsa",
    "Sahibganj",
    "Saiha",
    "Salem",
    "Samastipur",
    "Samba",
    "Sambalpur",
    "Sangli",
    "Sangrur",
    "Sant Kabir Nagar",
    "Sant Ravidas Nagar",
    "Saran",
    "Satara",
    "Satna",
    "Sawai Madhopur",
    "Sehore",
    "Senapati",
    "Seoni",
    "Seraikela Kharsawan",
    "Serchhip",
    "Shahdol",
    "Shahjahanpur",
    "Shajapur",
    "Shamli",
    "Sheikhpura",
    "Sheohar",
    "Sheopur",
    "Shimla",
    "Shimoga",
    "Shivpuri",
    "Shopian",
    "Shravasti",
    "Sibsagar",
    "Siddharthnagar",
    "Sidhi",
    "Sikar",
    "Simdega",
    "Sindhudurg",
    "Singrauli",
    "Sirmaur",
    "Sirohi",
    "Sirsa",
    "Sitamarhi",
    "Sitapur",
    "Sivaganga",
    "Siwan",
    "Solan",
    "Solapur",
    "Sonbhadra",
    "Sonipat",
    "Sonitpur",
    "South  Parganas",
    "South Delhi",
    "South Garo Hills",
    "South Goa",
    "South Sikkim",
    "South Tripura",
    "South West Delhi",
    "Sri Muktsar Sahib",
    "Srikakulam",
    "Srinagar",
    "Subarnapur (Sonepur)",
    "Sultanpur",
    "Sundergarh",
    "Supaul",
    "Surat",
    "Surendranagar",
    "Surguja",
    "Tamenglong",
    "Tarn Taran",
    "Tawang",
    "Tehri Garhwal",
    "Thane",
    "Thanjavur",
    "The Dangs",
    "Theni",
    "Thiruvananthapuram",
    "Thoothukudi",
    "Thoubal",
    "Thrissur",
    "Tikamgarh",
    "Tinsukia",
    "Tirap",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Tonk",
    "Tuensang",
    "Tumkur",
    "Udaipur",
    "Udalguri",
    "Udham Singh Nagar",
    "Udhampur",
    "Udupi",
    "Ujjain",
    "Ukhrul",
    "Umaria",
    "Una",
    "Unnao",
    "Upper Siang",
    "Upper Subansiri",
    "Uttar Dinajpur",
    "Uttara Kannada",
    "Uttarkashi",
    "Vadodara",
    "Vaishali",
    "Valsad",
    "Varanasi",
    "Vellore",
    "Vidisha",
    "Viluppuram",
    "Virudhunagar",
    "Visakhapatnam",
    "Vizianagaram",
    "Vyara",
    "Warangal",
    "Wardha",
    "Washim",
    "Wayanad",
    "West Champaran",
    "West Delhi",
    "West Garo Hills",
    "West Kameng",
    "West Khasi Hills",
    "West Siang",
    "West Sikkim",
    "West Singhbhum",
    "West Tripura",
    "Wokha",
    "Yadgir",
    "Yamuna Nagar",
    "Yanam",
    "Yavatmal",
    "Zunheboto"
  ];

  static const List<String> designation = [
    "Accounting",
    "Interior Design",
    "Bank",
    "Content Writing",
    "Consultant",
    "Engineer",
    "Export Import",
    "Merchandiser",
    "Security",
    "HR/Admin",
    "Hotel",
    "Application Programming",
    "Client Server",
    "DBA",
    "Ecommerce",
    "ERP",
    "VLSI",
    "Mainframe",
    "Middleware",
    "Mobile",
    "Network administrator",
    "IT Industry",
    "Testing",
    "System Programming",
    "EDP",
    "Telecom Software",
    "Telecom",
    "BPO/ Telecaller",
    "Legal",
    "Marketing",
    "Packaging",
    "Pharma",
    "Maintenance",
    "Logistics",
    "Sales",
    "Secretary",
    "Corporate Planning",
    "Site Engineering",
    "Film",
    "Teacher",
    "Airline",
    "Graphic Designer",
    "Shipping",
    "Analytics",
    "Business Intelligence",
    "Accountant",
    "Advertising",
    "Agriculture",
    "Animation",
    "Architect",
    "Automobile",
    "Aviation",
    "Bouncer",
    "Beautician",
    "Brewery",
    "Sanitary",
    "Chemical",
    "Cameraman",
    "Consumer Durables",
    "Courier",
    "Defence",
    "Content Writer",
    "Electrician",
    "Export Import",
    "FMCG",
    "Facility Management",
    "Fertilizers",
    "Food Processing",
    "Fresher",
    "Gems Jewellery",
    "Glass",
    "Air Conditioning",
    "Bartender",
    "Networking",
    "Caretaker/Nanny",
    "Industrial",
    "Insurance",
    "KPO",
    "Carpenter",
    "Media",
    "Dotcom",
    "Entertainment",
    "Medical",
    "Mining",
    "NGO",
    "Automation",
    "Oil and Gas",
    "Paper",
    "Cashier",
    "Printing",
    "Publishing",
    "Real Estate",
    "Recruitment ",
    "Retail",
    "Cleaner/Washer",
    "Electronics",
    "Construction/Laborer",
    "Steel",
    "Business Analyst",
    "Telecom",
    "Textiles",
    "Tyres",
    "Water Treatment",
    "Fitness Trainer",
    "Ecommerce",
    "Internet",
    "Control Room Operator",
    "Cook/Chef",
    "Counsellor",
    "Data Collection/Survey",
    "Data Entry /Back Office",
    "Data Scientist",
    "Delivery/Collections",
    "Doctor",
    "Draftsman",
    "Driver",
    "DTP Operator/Print Consultant",
    "Dubbing Artist",
    "Editor",
    "Electroplater",
    "Event Planner",
    "Financial Advisor",
    "Fire Fighter",
    "Fitter",
    "Floor Manager",
    "Foundryman",
    "Gardener",
    "Handryman",
    "Help Desk Executive",
    "Hospitality Executive",
    "Host/Hostess",
    "Housekeeping",
    "Insurance Consultant",
    "IT Hardware & Network Engineer",
    "IT Software - Developer",
    "IT Software - QA/Test Engineer",
    "IT Software - Web Designer",
    "Lab Assistant",
    "Language Translator",
    "Librarian",
    "Life Guard",
    "Lighting Technician",
    "Maid",
    "Market Research Analyst",
    "Mechanic",
    "Medical Assistant",
    "Medical Representative",
    "Microbiologist",
    "MIS Executive",
    "Moulder",
    "Nurse",
    "Nutritionist/Dietician",
    "Office Assistant/Helper",
    "Operator/Machinist",
    "Optometrist",
    "Packager",
    "Painter",
    "Pest Control Executive",
    "Pharmacist",
    "Photographer",
    "Plumber",
    "Product Manager",
    "Program/Project Manager",
    "Projectionist",
    "Public Relations",
    "Purchase Executive",
    "Quality and Inspection",
    "Receptionist/Front Office",
    "Reporter",
    "Rigger",
    "Safety Officer",
    "SAP Consultant",
    "Scientist/Research",
    "Security/Guard",
    "Sheet Metal Worker",
    "Software Architect",
    "Soldering Operator",
    "Sound Engineer",
    "Sports Trainer",
    "Tailor",
    "Ticketing Executive",
    "Trainer",
    "Transport Supervisor",
    "Videographer",
    "Waiter/Steward",
    "Ward Boy",
    "Warehouse Executive",
    "Welder",
    "Wireman",
  ];
}
